os: Visual Studio 2015
environment:
  matrix:
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: beta
      target: i686-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup install nightly
  - rustc -vV
  - cargo -vV
build: false
test_script:
  - make.bat
after_test:
  - cd build\windows
  - 7z a refunct-tas-windows.zip *
  - move menu.lua tas.lua && 7z a practice-windows.zip refunct-tas.exe rtil.dll prelude.lua teleportbutton-prelude.lua tas.lua Config.toml
matrix:
  allow_failures:
    - channel: beta
    - channel: nightly
artifacts:
  - path: build\windows\refunct-tas-windows.zip
  - path: build\windows\practice-windows.zip
deploy:
  provider: GitHub
  artifact: /.*\.zip/
  auth_token:
    secure: 0VDU7wyyTjt7PotLoL6zwNjlWXiYekw4p/FI5C9/YY54mxiSnGwE9rPh6nIr8vA4
  draft: true
  on:
    channel: stable
    appveyor_repo_tag: true
