[package]
name = "rtil_derive"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.30", features = ["full"] }
quote = "0.6.12"
proc-macro2 = "0.4.27"
